module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e0e3e5',
        'surface-container': '#eceef0',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#4edea3',
        'on-surface': '#191c1e',
        'on-secondary-fixed': '#0b1c30',
        'primary-container': '#131b2e',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        background: '#f7f9fb',
        'secondary-fixed': '#d3e4fe',
        'primary-fixed': '#dae2fd',
        'on-secondary': '#ffffff',
        outline: '#76777d',
        'on-background': '#191c1e',
        'on-primary-container': '#7c839b',
        'inverse-primary': '#bec6e0',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-container': '#002113',
        primary: '#000000',
        'outline-variant': '#c6c6cd',
        'on-primary-fixed': '#131b2e',
        'on-error': '#ffffff',
        'secondary-container': '#d0e1fb',
        'primary-fixed-dim': '#bec6e0',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        secondary: '#505f76',
        'inverse-surface': '#2d3133',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#54647a',
        'on-primary': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-tertiary-fixed': '#002113',
        'surface-tint': '#565e74',
        tertiary: '#000000',
        'on-surface-variant': '#45464d',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container-low': '#f2f4f6',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#38485d',
        surface: '#f7f9fb',
        'on-tertiary-container': '#009668',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        md: '16px',
        sm: '8px',
        lg: '24px',
        gutter: '24px',
        'container-max': '1280px',
        xs: '4px',
        xl: '48px',
        base: '4px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
        'display-lg': ['Inter'],
        'body-sm': ['Inter'],
        'title-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
